### ISSUE TITLE
SDR object members are non-standarised names

### ISSUE THREAD

**Issue by jm-rivera** [ONEcampaign/bblocks#113]
The SDR object can optionally filter for certain members when the user gets the data. It is currently unclear how the user would know the right spelling of the "member" names used by the IMF.

@lpicci96 lets discuss a way to improve this. I think we could make use of the regular expression matching done by `country_converter` to achieve this. Have a look at the `convert_id()` function, which could handle this in the background. For "members" which aren't countries, `convert_id()` takes an optional, additional mapping dictionary which could help capture those cases.

**Comment by lpicci96** [comment]
closing this as it is will be dealt with in policy_etl
