### ISSUE TITLE
Alter ImportData parent class

### ISSUE THREAD

**Issue by lpicci96** [ONEcampaign/bblocks#124]
Alter ImportData parent class to make `data` attribute inaccessible. Users must use the getter method or the `indicator` attribute. 
Change `self.data` to `self.__data`

**Comment by jm-rivera** [comment]
Here is a suggested implementation

```python
@dataclass
class ImportData(ABC):
    _data: dict[str, pd.DataFrame] = field(default_factory=dict)
    _raw_data: pd.DataFrame = None

    @abstractmethod
    def load_data(self, **kwargs) -> ImportData:
        """Load the _data saved on disk"""
        pass

    @abstractmethod
    def update_data(self, **kwargs) -> ImportData:
        """Update object _data"""
        pass

    def get_data(self, indicators: str | list, **kwargs) -> pd.DataFrame:
        """Get the _data as a Pandas DataFrame"""
        df = pd.DataFrame()

        if indicators == "all":
            indicators = self._data.values()

        if isinstance(indicators, str):
            indicators = [indicators]

        if isinstance(indicators, list):

            for _ in indicators:
                if _ not in self._data:
                    raise ValueError(
                        f"{_} has not been loaded or is an invalid indicator."
                    )

            indicators = [self._data[_] for _ in indicators if _ in list(self._data)]

        for _ in indicators:
            df = pd.concat([df, _], ignore_index=True)

        return df
```

**Comment by lpicci96** [comment]
I generally agree with this new structure. A few thought/questions:
- `_raw_data` would only be used in those cases where you have to get all the data at once but not necessarily want to load it all correct?
- Should `load_data` not require an `indicator` parameter? 
- Instead of `all` shouldn't `get_data` parameter be `None` to retrieve all data?
- **kwargs should be removed 
- `get_data` should check if _data is empty
- instead of raising an error if an indicator is not found, it should raise a warning and still return the existing indicators
- `get_data` should check if the dataframe is empty before returning it

It may be useful to also write the tests for the base class before merging

**Comment by lpicci96** [comment]
I think there is a bug in `get_data`
```
if indicators == "all":
            indicators = self._data.values()
```

This will create a list of dataframes instead of strings

**Comment by jm-rivera** [comment]
> I generally agree with this new structure. A few thought/questions:
> 
> * `_raw_data` would only be used in those cases where you have to get all the data at once but not necessarily want to load it all correct?

That is correct. Several sources may need this but definitely not all. Hence it is happy to be empty.

> * Should `load_data` not require an `indicator` parameter?
Perhaps but that could be a child class thing to implement (in case we decide indicator is not the right word in some cases)


> * Instead of `all` shouldn't `get_data` parameter be `None` to retrieve all data?
It's an interesting idea. But in the spirit of 'explicit is better' then 'all' is better. None literally means 'None'.

> * **kwargs should be removed
Not for the ABC, otherwise you can't pass anything not defined there

> * `get_data` should check if _data is empty
Indeed, I'll modify

> * instead of raising an error if an indicator is not found, it should raise a warning and still return the existing indicators
Good idea, I'll modify

> * `get_data` should check if the dataframe is empty before returning it
Good idea, I'll log a warning

> It may be useful to also write the tests for the base class before merging
Yes!

**Comment by jm-rivera** [comment]
```python

def get_data(self, indicators: str | list = "all", **kwargs) -> pd.DataFrame:
        """Get the _data as a Pandas DataFrame"""
        if self._data is None:
            raise RuntimeError("No data or indicators have been loaded")

        df = pd.DataFrame()
        indicators_ = []

        if indicators == "all":
            indicators_ = self._data.values()

        if isinstance(indicators, str):
            indicators = [indicators]

        if isinstance(indicators, list):

            for _ in indicators:
                if _ not in self._data:
                    logger.warning(f"{_} not loaded or is an invalid indicator.")

            indicators_ = [self._data[_] for _ in indicators if _ in list(self._data)]

        if len(indicators_) == 0:
            logger.warning("No indicators were loaded. Returning empty dataframe.")

        for _ in indicators_:
            df = pd.concat([df, _], ignore_index=True)

        return df
```

New version @lpicci96

**Comment by lpicci96** [comment]
could rewrite the return to ` return pd.concat([df, _] for _ in indicators_, ignore_index=True)`


We can also reduce the number of for loops in the list condition by:

```
for _ in indicators:
    if _ not in self._data:
        logger.warning(f"{_} not loaded or is an invalid indicator.")
        invalid_indicators.append(_)
    else:
        indicators_.append(self._data[_])
```
