### ISSUE TITLE
World Bank getter changes object state

### ISSUE THREAD

**Issue by lpicci96** [ONEcampaign/bblocks#92]
The `WorldBankData` getter method `get_data()` modifies the state of the object

https://github.com/ONEcampaign/bblocks/blob/68967b40d69f8629e224e665ae152a4248557bf0/bblocks/import_tools/world_bank.py#L151

data is replaced with the modified dataframe

https://github.com/ONEcampaign/bblocks/blob/68967b40d69f8629e224e665ae152a4248557bf0/bblocks/import_tools/world_bank.py#L180

**Comment by jm-rivera** [comment]
#161 will address this issue.
